---
name: Roundcube
version: dev
slug: roundcube
description: Roundcube webmail client
url: https://github.com/erik73/hassio-addons
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_stream: true
panel_icon: mdi:email
map:
  - ssl
services:
  - mysql:need
ports:
  80/tcp: null
ports_description:
  80/tcp: Roundcube
hassio_api: true
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  disableSessionRenewal: false
schema:
  certfile: str
  keyfile: str
  ssl: bool
  disableSessionRenewal: bool
